library(rmarkdown)
# render_site("./source/ma690.Rmd")
# render_site("./source/index.Rmd")
# render_site("./source/pub.Rmd")
# render_site("./source/teaching.Rmd")
# render_site("./source/")
render_site("./source/talks.Rmd")
