---
title: "MA 212M: Mathematical Statistics"
output:
   html_document:
    toc: true
    toc_float: true
---

---

# Course Syllabus

* Probability: Probability spaces, random variables and random vectors,
  functions of random vectors, univariate and multivariate distributions,
  mathematical expectations, moment generating functions, convergence in
  probability and in distribution and related results; Sampling distributions.

* Statistics: Point estimation - estimators, sufficiency, completeness, minimum
  variance unbiased estimation, maximum likelihood estimation, method of
  moments, Cramer-Rao inequality, consistency; Interval estimation; Testing of
  hypotheses - tests and critical regions, Neymann-Pearson lemma, uniformly most
  powerful tests, likelihood ratio tests; Correlation and linear regression.

---

# Text Books

* Introduction to Mathematical Statistics by R. V. Hogg, J. W. McKean and A. Craig.
* Introduction to Probability Models by S. M. Ross.

# Reference Books

* An Introduction to Probability and Statistics by V. K. Rohatgi and A. K. Md. E. Saleh.

---

# Evaluation

Weights in different examinations are as follows:

* **Quiz I:** 15% (February 06 during class)
* **Mid-semester examination:** 30% (March 07 from 9 am to 11 am)
* **Quiz II:** 15% (April 10 during class)
* **End-semester examination:** 40% (May 09 from 9 am to 12 am)

For each examination, linear scaling will be used (if needed).

An F grade will be awarded if you obtain less than 20% of total marks after the end semester examination.

---

# Course Materials

## Lecture Slides
* [Topic 00: Introduction](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQBlfjyEkwqmR4Y45B6LGhaAAZdfbbuxolcqz-vY07fuP1c?e=JSc6wp)
* [Topic 01: Probability](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQA1XlgKZFReS4nXfUrPjoX-AeV9sIJcNLwzHpTtkfRCLBc?e=2TMCHE)
* [Topic 02: Random Variable](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQBLlgzMLTY3S5uBv9vN9ZiJAYzQbfBV8RulKMvcWBDvK1w?e=WDKI8t)
* [Topic 03: Random Vector](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQCVBpVN2k_uTbt43zfBNqSCAeoDviyjcehebc9fxtBgK0Q?e=rrOF11)
* [Topic 04: Modes of Convergence](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQA4dBg3cWLqTaXrtd9DnjhJAWEM-Jo70Ojyru12N3UExwA?e=eu8smO)
* [Topic 05: Sampling Distributions](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQDsOjOz8GPXRrCP2OO8dysnAcpA4jL0zc7i6VsS1jyJUbI?e=WH8ZHJ)
* [Topic 06: Point Estimation](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQATqpdi-SvNR7TUaFLqXfaaAVkcDu56ebAAE3ax-59YdJQ?e=6LWZ3B)
* [Topic 07: Interval Estimation](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQDmFLGEdPaaSLGiGFO27WPvAaucDMJiqFa2RNPX2b0qzGI?e=DDFfl3)
* [Topic 08: Testing of Hypotheses](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQAipCp0NN0MQasxXSdulbAgAWZ5tPLD4aZ1ZCRcN86r2Zk?e=zfhGll)
* [Topic 09: Simple Linear Regression](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQB3Z5ezzRT_SIju680Jq3FsAbrShAbdNK4V5DUH0eDrMWc?e=mBgB5J)
* [Topic 10: Multiple Linear Regression](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQAgU8BcRWi4Q66nzpzJpJCNAaPE5ggwgIThX5xewUihgT4?e=g0vzUH)
* [Topic 11: Logistic and Poisson Regression](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQD0W84UdQwXRpx2b4mDBrkIAd8JWUfwOMdZM9EvehrVfio?e=aU91rD)

## Problem Sets
* [Problem Set 01](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQAYHg_deEoBT4fK6NXm7iU-AfJS7AstjYUhu3GAOoCCQCA?e=wt4tr3)
* [Problem Set 02](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQCxYuCatq4pQbNArwSJqy1GAR541OoIo6lXajb_U3DYtjc?e=Duro5V)
* [Problem Set 03](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQCSt6IElZpcTZmD1JPMgZmkAYaHIlPwWJcIHc5YQ761amk?e=zXzP2m)
* [Problem Set 04](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQA_TbecLRAGTbu-_GusrUhVAYdsud8a8-A6-9ACDCcQQQs?e=XIKf3X)
* [Problem Set 05](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQD_YMv1boBLRYtY9W5BjbkaAQneTqrrrSdVl2svXeCODdo?e=0dR5te)
* [Problem Set 06](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQDLiv8t6VsiSIIqmjxbWoulAdKUNCvKMVIbwhTOEy6eB5A?e=fWgNYr)
* [Problem Set 07](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQDHub_8T3oWQZy9pjH5wlM8Aei5lgNU6ESgaSO9FNgWqDw?e=lZwiNC)
* [Problem Set 08](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQBGdPM0xvmeTbeuaxTdCh5_AYocFPcUScjS9XH6tGoS3uM?e=c9ORAG)
* [Problem Set 09](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQBGcz35y9fmRKd9aK2-8IBFAaFspyq-gf3myOSbYw6CYI0?e=MkbJXU)
* [Problem Set 10](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQBCm3a0__DbRJPwvLyq9wb8AS77kxu3RoUVF_klasHmONE?e=0zszjP)
* [Problem Set 11](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQAwhN5onpTURJ2lfJLqQvWYAUi2Ptexj4OH9ZkbOGzG18M?e=w6ddVp)
<!-- * [Problem Set 12]() -->
