---
title: "MA 212M: Understanding Statistical Learning Theory"
---

## Course Syllabus

* Linear Regression
* Linear Model Selection and Regularization
* Classification
* Non-linear Regression
* Tree-based Methods
* Support Vector Machine
* Deep Learning
* Multiple Testing
* Survival Analysis

## Books

### Text Books

* An Introduction to Statistical Learning with Application in R by G. James, D. Witten, T. Hastie, R. Tibshirani [Softcopy](https://www.statlearning.com/)
* An Introduction to Statistical Learning with Application in Python by G.James, D. Witten, T. Hastie, R. Tibshirani, J. Taylor [Softcopy](https://www.statlearning.com/)

### Reference Book

* The Elements of Statistical Learning} by T. Hastie, R. Tibshirani, J. Friedman [Softcopy](https://hastie.su.domains/ElemStatLearn/)

## Evaluation

<!-- Will be informed between August 04 -- 06, 2026 -->
The breakdown of the evaluation components and their respective weights is as follows:

* **Project I:** 20% (Selected topics will be assigned for self-study throughout the semester. Students are expected to independently study and present these topics as part of a continuous evaluation process.)
* **Project II:** 30% (Students are expected to complete a comprehensive data analysis project and present their findings. Presentations will be scheduled toward the end of the semester. Further details will be provided in class.)
* **Mid-semester examination:** 20% (September 19 from 9 am to 11 am)
* **End-semester examination:** 30% (November 20 from 9 am to 12 am)

## Course Materials

To download lecture slides on statistical inference and linear regression, please [click here](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQBb1jnD_ftXR7mB7sR_oJCGAQ1hvvSqBu48G9HHCVqI1Ms?e=fNhWKX)

### Lecture Slides
* [Topic 00: Introduction](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQBvPOjpiacRQoIVijlrtGbYAdH0OHZUo9D-PH-HXDJzhuI?e=HCaCmA)
* [Topic 01: Linear Regression (A Review)](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQD8pgQy6-vjSLMwE5GK3F9-AWaYRkuiqVw8C2wMO1hQI24?e=2xKB7k)
* [Topic 02: Statistical Learning (An Overview)](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQAsam6ZTlAKSaIxIbA0AxQzAe-dfhAkmPcv78x4PVpAoYg?e=6tjwl9)
* [Topic 03: Model Selection in Linear Regression](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQC3306-Y3kUTJ5zXS2iNNqzAeee9o39_lVfVzAZugTXh4g?e=4gPQLK)

<!-- ## Problem Sets -->
<!-- * [Problem Set 01](https://iitgoffice-my.sharepoint.com/:b:/g/personal/aganguly_iitg_ac_in/IQAYHg_deEoBT4fK6NXm7iU-AfJS7AstjYUhu3GAOoCCQCA?e=wt4tr3) -->
