---
title: "Academics"
---

# Education

* PhD in Statistics (2013), Department of Mathematics and Statistics, IIT
  Kanpur, Kanpur - 208 016, India. [Thesis](thesis.pdf)
* Master of science in Statistics (2008), Department of Mathematics and
  Statistics, IIT Kanpur, Kanpur - 208 016, India.
* Bachelor of science in Statistics (2006), Department of Statistics,
  Maulana Azad College, Kolkata - 700 013, India.
* Higher Secondary Examination (2003), West Bengal Council of Higher
  Secondary Examination, India.
* Secondary (Madhyamik) Examination (2001), West Bengal Board of Secondary
  Education, India.


# Work Experiences

1. Assistant Professor at the Department of Mathematics, Indian Institute of
   Technology Guwahati from June, 2016 to present.
1. Assistant Professor (on contract) at the Department of Applied Sciences,
   Indian Institute of Information Technology Allahabad from January, 2016 to
   June 2016.
1. Visiting Faculty (Adhoc) at the Department of Applied Sciences, Indian
   Institute of Information Technology Allahabad from December, 2014 to January,
   2016.
1. Post-doctoral fellow (Dr. DS Kothari Fellowship form UGC) at the Department
   of Statistics, Sabitribai Phule Pune University, Pune from September 2013 to
   December, 2014.
1. Visiting Scientist at Indian Statistical Institute, Chennai from April, 2013
   to September, 2013.


# Editorial Activities

1. Associate Editor of [*Mathematical Methods of
   Statistics*](https://link.springer.com/journal/12004), Springer Nature, from
   2025 to present.

