---
title: "MA 682 : Statistical Inference"
---

---

## Lecture Slides
* [Topic 0: Review of Probability](./MA682/LectureSlides/topic0.pdf)
* [Topic 1: Monte Carlo Simulation](./MA682/LectureSlides/topic1.pdf)
* [Topic 2: Point Estimation](./MA682/LectureSlides/topic2.pdf) (Updated on Feb 05, 2024)
* [Topic 3: Interval Estimation](./MA682/LectureSlides/topic3.pdf) (Updated on Feb 09, 2024)
* [Topic 4: Hypothesis Testing](./MA682/LectureSlides/topic4.pdf) (Updated on Mar 11, 2024)
* [Topic 5: Linear Regressions](./MA682/LectureSlides/topic5.pdf) (Updated on Mar 28, 2024)
   + [Supplementary Document for Simple Linear Regression](./MA682/Supplementary/topic5Suppl.pdf)
   + [R codes for Simple Linear Regression](./MA682/Rcodes/slr.R)
   + [Heights Data-set](./MA682/DataSets/heights.csv)
* [Topic 6: Non-parametric Tests](./MA682/LectureSlides/topic6.pdf) (Updated on Apr 20, 2024)

---

## Problem Sets
* [Problem Set 01](./MA682/ProblemSets/P01.pdf)
* [Problem Set 02](./MA682/ProblemSets/P02.pdf)
* [Problem Set 03](./MA682/ProblemSets/P03.pdf)
* [Problem Set 04](./MA682/ProblemSets/P04.pdf)
* [Problem Set 05](./MA682/ProblemSets/P05.pdf)
* [Problem Set 06](./MA682/ProblemSets/P06.pdf)
* [Problem Set 07](./MA682/ProblemSets/P07.pdf)
* [Problem Set 08](./MA682/ProblemSets/P08.pdf)
