---
title: "Publications"
---

# Papers in Refereed Journal

1. Biswas, S., **Ganguly, A.**, and Mitra, D. (2025), [Reliability Analysis of Load-sharing Systems using a Flexible Model with Piecewise Linear Functions](https://onlinelibrary.wiley.com/doi/10.1002/asmb.2934){target="_blank"}, *Applied Stochastic Models in Business and Industry*, 41:e2934. [[Preprint]](./papers/2025BGM.pdf){target="_blank"}
1. Agrawal, A., **Ganguly, A.**, and Mitra, D. (2025), [Modelling Competing Risks Data by a Bivariate Model with Singularity Originating from a Shock Model using the Lehmann Family of Distributions](https://www.tandfonline.com/doi/full/10.1080/27684520.2025.2480181){target="_blank"}, *Research in Statistics*. [[Preprint]](./papers/2025AGM.pdf){target="_blank"}
1. Agrawal, A., Mitra, D. and **Ganguly, A.** (2024), [A Model for Censored Reliability Data with Two Dependent Failure Modes and Prediction of Future Failures](https://www.tandfonline.com/doi/full/10.1080/08982112.2024.2321839){target="_blank"}, *Quality Engineering*, 37:1-14. [[Preprint]](./papers/2024AMG.pdf){target="_blank"}
1. **Ganguly, A.**, Mitra, D., Balakrishnan N. and Kundu, D. (2024), [A Flexible Model based on Piecewise Linear Approximation for the Analysis of Left Truncated Right Censored Data with Covariates, and Applications to Worcester Heart Attack Study Data and Channing House Data](https://onlinelibrary.wiley.com/doi/10.1002/sim.9954){target="_blank"}, *Statistics in Medicine*, 43:233--255.
   <!-- [[Preprint]](./papers/2023GMBK.pdf){target="_blank"} -->
1. Samanta, D., **Ganguly, A.**, Gupta, A. and Kundu, D. (2019), [On Classical and Bayesian Order Restricted Inference for Multiple Exponential Step Stress Model](https://www.tandfonline.com/doi/full/10.1080/02331888.2018.1526285){target="_blank"}, *Statistics*, 53:177--195. [[Preprint]](./papers/2019SGGK.pdf){target="_blank"}
1. Samanta, D., Kundu, D. and **Ganguly, A.** (2018), [Order Restricted Bayesian Analysis of a Simple Step Stress Model](https://link.springer.com/article/10.1007/s13571-017-0139-9){target="_blank"}, *Sankhya, Series B.*, 80:195--221. [[Preprint]](./papers/2018SKG.pdf){target="_blank"}
1. Koley, A., Kundu, D. and **Ganguly, A.** (2017), [Analysis of Type-II Hybrid Censored Competing Risks Data](https://www.tandfonline.com/doi/full/10.1080/02331888.2017.1358271){target="_blank"}, *Statistics*, 51:1304--1325. [[Preprint]](./papers/2017KKG.pdf){target="_blank"}
1. Hanagal, D., Pandey, A. and **Ganguly, A.** (2017), [Correlated Gamma Frailty Models for Bivariate Survival Data](https://www.tandfonline.com/doi/full/10.1080/03610918.2015.1085559){target="_blank"}, *Communication in Statistics - Simulation and Computation*, 46:3627--3644.
   <!-- [[Preprint]](./papers/2017HPG.pdf){target="_blank"} -->
1. Samanta, D., **Ganguly, A.**, Kundu, D., and Mitra, S. (2017), [Order Restricted Bayesian Inference for Exponential Simple Step-stress Model](https://www.tandfonline.com/doi/full/10.1080/03610918.2014.992540){target="_blank"}, *Communication in Statistics - Simulation and Computation*, 46:1113--1135. [[Preprint]](./papers/2017SGKM.pdf){target="_blank"}
1. Kundu, D., Mitra, D, and **Ganguly, A.** (2017), [Analysis of Left Truncated Right Censored Competing Risks Data](https://www.sciencedirect.com/science/article/pii/S016794731630247X){target="_blank"}, *Computational Statistics and Data Analysis*, 108:12--26. [[Preprint]](./papers/2017KMG.pdf){target="_blank"}
1. **Ganguly, A.** and Kundu, D. (2016), [Analysis of Simple Step-stress Model in Presence of Competing Risks](https://www.tandfonline.com/doi/full/10.1080/00949655.2015.1096362){target="_blank"}, *Journal of Statistical Computation and Simulation*, 86:1989--2006. [[Preprint]](./papers/2016GK.pdf){target="_blank"}
1. **Ganguly, A.**, Kundu, D., and Mitra, S. (2015), [Bayesian Analysis of Simple Step-stress Model under Weibull Lifetimes](https://ieeexplore.ieee.org/document/6969122){target="_blank"}, *IEEE Transaction on Reliability*, 64:473--485. [[Preprint]](./papers/2015GKM.pdf){target="_blank"}
1. Mitra, S., **Ganguly, A.**, Samanta, D., and Kundu, D. (2013), [On Simple Step-stress Model for Two-parameter Exponential Distribution](https://www.sciencedirect.com/science/article/pii/S1572312713000415){target="_blank"}, *Statistical Methodology*, 15:95--114. [[Preprint]](./papers/2013MGSK.pdf){target="_blank"}
1. Kundu, D., Samanta, D., **Ganguly, A.**, and Mitra, S. (2013), [Bayesian Analysis of Different Hybrid and Progressive Life Tests](https://www.tandfonline.com/doi/full/10.1080/03610918.2011.654027){target="_blank"}, *Communication in Statistics - Simulation and Computation*, 42:2160--2173. [[Preprint]](./papers/2013KSGM.pdf){target="_blank"}
1. **Ganguly, A.**, Mitra, S., Samanta, D., and Kundu, D. (2012), [Exact Inference for the Two-Parameter Exponential Distribution Under Type-II Hybrid Censoring](https://www.sciencedirect.com/science/article/pii/S0378375811003120){target="_blank"}, *Journal of Statistical Planning and Inference*, 142:613--625. [[Preprint]](./papers/2012GMSK.pdf){target="_blank"}


# Book

* Kundu, D. and Ganguly, A. (2017), [Analysis of Step-stress Models: Existing Results and Recent Developments](https://www.sciencedirect.com/book/9780128097137/analysis-of-step-stress-models){target="_blank"}, Elsevier/Academic Press, London, United Kingdom.
