---
title: "Students"
---

# PhD Students

  1. Dr. Shilpi Biswas (July 2019 - October 2025): Area: Statistical modeling
     of load sharing systems. Current Position: Visiting Scientist, ISI Kolkata.
  1. Mr. Sourav Saha (July 2022 - Present): Area: Statistical analysis of
     bivariate left truncated right censored data.
  1. Mr. Arpan Sanyal (July 2023 - Present): Area: AUC estimation for a ROC.

<!-- # ```{r table2, echo=FALSE, message=FALSE, warnings=FALSE, results='asis'} -->
<!-- # tabl <- " -->
<!-- # | Sl. No. | Name | Duration of PhD | Area of PhD thesis | Current Position | -->
<!-- # |:--------|:----:|----------------:|-------------------:|-----------------:| -->
<!-- # | 1. | Dr. Shilpi Biswas | July 2019 to October 2025 | Statistical modeling of load-sharing systems | Visiting Scientist, ISI Kolkata | -->
<!-- # | 2. | Mr. Sourav Saha | July 2022 to present | Statistical analysis of bivariate left truncated and right censored data | | -->
<!-- # | 3. | Mr. Arpan Sanyal | July 2023 to present | Estimation of AUC of ROC | |" -->
<!-- # cat(tabl) -->
<!-- # ``` -->

# MSc Students

  1. Ms. Shivika Rani (2025). Project Title: GLMs: Bridging linear and
     non-linear models (Reading project)
  1. Mr. Aniket Chaudhary (2025). Project Title: Central limit theorems (Reading
     project)
  1. Mr. Arvind Kumar (2024). Project Title: Survival analysis using Cox
     regression model (Reading project).
  1. Mr. Saneilie Keyho (2024). Project Title: Kaplan-meier estimator and its
     application (Reading project).
  1. Mr. Nilmadhab Tewari (2023). Project Title: Theoretical foundations and
     properties of copula.
  1. Ms. Priyanka Singh (2023). Project Title: On one shot device testing.
  1. Ms. Deepika (2020). Project Title: Lifetime data analysis.
  1. Mr. Arijit Roy (2018). Project Title: Discriminating among different
     models for step-stress life test.
  1. Mr. Santanu Datta (2017). Project Title: Bayesian analysis of simple
     step-stress tampered random variable model under generalized
     exponential lifetimes.


# BTech Students

  1. Ms. Ramineni Hardhika and Mohd Fahad Javed (2025-2026). Project Title:
     Application of Bayesian Logistic Regression to Biomedical Data for
     Modelling Heart Attack Risk. 
  1. Mr. Lakshya Kohli and Mr. Daksh Raj (2024 - 2025). Project Title: Bayesian
     analysis of left truncated and right censored data using splines.
  1. Mr. Harshul Gupta and Mr. Harsh (2023 - 2024). Project Title: Improving
     Bayesian estimation for censored data with Weibull model using modified
     SMOTE.
  1. Mr. Dasari Sainaren and Mr. Mandala Yatish Ramkumar (2022 - 2023). Project
     Title: Bayesian sampling plan for the Weibull distribution with generalized
     Type-I hybrid censoring scheme.
  1. Mr. Kaushal Chhalani and Mr. Manav Chirania (2021 - 2022). Project
     Title: Bayesian analysis of left truncated right censored data in the
     presence of dependent competing risks.
  1. Mr. Aakash Agarwal (2019 - 2020). Project Title: Step-stress analysis
     in the presence of lag effect for log-normal lifetimes.
  1. Mr. Abhishek Dogra and Mr. Animesh Kumar (2019 - 2020). Project Title:
     Analysis of left truncated right censored data in the presence of
     dependent competing risks.
  1. Mr. Akash Mahalik and Mr. Tarun Genwa (2018 - 2019). Project Title:
     Reliability dimention in review platform Yelp.
